// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_Movies.Models;

namespace Mission06_Movies.Migrations
{
    [DbContext(typeof(AddMovieContext))]
    [Migration("20230221025710_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_Movies.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Animated"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Horror"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Action/Adventure"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Drama"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Television"
                        });
                });

            modelBuilder.Entity("Mission06_Movies.Models.MovieResponse", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            CategoryID = 2,
                            Director = "Dean DeBlois",
                            Edited = false,
                            LentTo = "",
                            Notes = "",
                            Rating = "PG",
                            Title = "How To Train Your Dragon",
                            Year = 2010
                        },
                        new
                        {
                            MovieID = 2,
                            CategoryID = 2,
                            Director = "Joel Crawford",
                            Edited = false,
                            LentTo = "",
                            Notes = "Best Movie Ever",
                            Rating = "PG",
                            Title = "Puss In Boots: The Last Wish",
                            Year = 2022
                        },
                        new
                        {
                            MovieID = 3,
                            CategoryID = 1,
                            Director = "Perry Adelin Blake",
                            Edited = false,
                            LentTo = "",
                            Notes = "Award: Most Unfunny",
                            Rating = "PG",
                            Title = "The Master Of Disguise",
                            Year = 2002
                        });
                });

            modelBuilder.Entity("Mission06_Movies.Models.MovieResponse", b =>
                {
                    b.HasOne("Mission06_Movies.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
